name: Android CI

on:
  pull_request:
    branches-ignore:
      - ''
  push:
    branches-ignore:
      - ''
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Download lib/Mobile.arr
      run: |
        tag=$(curl -s "https://api.github.com/repos/ffip/mobileVLAN/releases/latest" | grep -o '"tag_name": ".*"' | sed 's/"tag_name": "//;s/"//')
        download_url="https://github.com/ffip/mobileVLAN/releases/download/$tag/libx.aar"
        wget $download_url -O libx.aar
        mv libx.aar app/libs/Mobile.aar

    - name: Build Signed Release APK
      uses: victorbnl/build-signed-apk@main
      with:
        keystore_file: key-store.jks
        keystore_password: 666666
        key_alias: hiper-key
        key_password: 666666

    - name : upload apk
      uses: actions/upload-artifact@v4.6.0
      with:
        name: HiPer
        path: app/build/outputs/apk/release/app-release.apk
